name    'lab42-solr'
version '2.0.0'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-solr'
summary 'Puppet module for solr'
description 'This module installs and manages solr. Check README for details.'
dependency 'puppetlabs/stdlib', '>= 0.1.0'
dependency 'lab42/stdlib42', '>= 2.0.0'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
dependency 'lab42/firewall', '>= 2.0.0'
