name    'lab42-solr'
version '2.0.1'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-solr'
summary 'Puppet module for solr'
description 'This module installs and manages solr. Check README for details.'
dependency 'lab42/puppi', '>= 2.0.0'
